version: "3"
services:
  app:
    build:
      context: .
      dockerfile: build/app/Dockerfile
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  mysql:
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
